services:
  import_data:
    image: alexandrewinger/shield:import_data
    container_name: import_data
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

  make_dataset:
    depends_on:
      import_data:
        condition: service_completed_successfully
    image: alexandrewinger/shield:make_dataset
    container_name: make_dataset
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

  create_users_db:
    image: alexandrewinger/shield:create_users_db
    depends_on:
      make_dataset:
        condition: service_completed_successfully
    container_name: create_users
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

  train_model:
    image: alexandrewinger/shield:train_model
    depends_on:
      create_users_db:
        condition: service_completed_successfully
    container_name: train_model
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

  api_shield:
    depends_on:
      train_model:
        condition: service_completed_successfully
    image: alexandrewinger/shield:api
    container_name: api
    ports:
      - "8000:8000" 
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network  


  monitoring_shield:
    image: alexandrewinger/shield:monitoring
    container_name: monitoring
    ports:
      - "8008:8008" 
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

  cron-monitor_shield:
    depends_on:
      train_model:
        condition: service_completed_successfully
    image: alexandrewinger/shield:cron-monitor
    container_name: cron-monitor
    ports:
      - "8009:8009" 
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network
    init: true

  streamlit_shield:
    depends_on:
      train_model:
        condition: service_completed_successfully
    image: alexandrewinger/shield:streamlit
    container_name: streamlit
    ports:
      - "8501:8501" 
    volumes:
      - type: volume
        source: prod-volume
        target: /home/volume
    networks:
      - shield-network

volumes:
  prod-volume:

networks:
  shield-network:
    driver: bridge

